# This is a basic workflow to help you get started with Actions

name: Code_Quality_Check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ '**' ]
    paths: [ '**.gd', '**.yml' ]
  pull_request:
    branches: [ '**' ]
    paths: [ '**.gd', '**.yml' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: '3.10'
            architecture: 'x64'

      # Runs a set of commands using the runners shell
      - name: Code Quality Check
        run: python code_quality_check.py
        continue-on-error: false
